---
version: "3.8"

services:
  seed:
    image: prologic/bitraft
    entrypoint:
      - timeout
      - -sTERM
      - "30"
    command:
      - /bitraft
      - -d=/tmp/bitraft
      - -b={{ GetInterfaceIP "eth0" }}:4920
    networks:
      - bitraft
    deploy:
      restart_policy:
        condition: none
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"

  cluster:
    image: prologic/bitraft
    command:
      - -d=/data
      - -j=seed:4920
      - -b={{ GetInterfaceIP "eth0" }}:4920
    networks:
      - bitraft
    deploy:
      mode: global

networks:
  bitraft:
    driver: overlay
    name: bitraft
    attachable: true
